name: Push and Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build and push Docker image

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get git tag
      id: tag
      run: echo "::set-output name=tag::$(git --no-pager describe --tags $(git rev-list --tags --max-count=1))"

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: Flamov
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: flamov/discord-bot-wow-status/discord-bot-wow-status
        tags: latest,${{ steps.tag.outputs.tag }}

  deploy:
    name: Deploy Docker image

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Deploy image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          echo ${{ secrets.PACKAGES_TOKEN }} | docker login docker.pkg.github.com -u Flamov --password-stdin
          docker-compose pull bot
          docker-compose up --no-deps -d bot
