name: Pull Request

on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci --unsafe-perm
    - name: Test ESLint
      run: npm run test:eslint
    - name: Test TypeScript files
      run: npm run test:typescript
    - name: Run unit tests
      run: npm run test:unit
